<a href="https://colab.research.google.com/github/hijinkim/TIL/blob/master/Python_Packages.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## numpy

In [33]:
import numpy as np

In [35]:
a0 = np.array(9)
print(a0)

9


In [36]:
a1 = np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [38]:
a2 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
a3 = np.array([[[1, 2],
                [3, 4]],
               [[5, 6],
                [7, 8]],
               [[9, 10],
                [11, 12]]])
print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [46]:
AR = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print(AR)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [41]:
AR.shape

(10,)

In [47]:
AR2 = AR.reshape(2, 8)
print(AR2)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [44]:
AR2.shape

(2, 5)

In [49]:
AR3 = AR.reshape(4, 2, 2)
print(AR3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [50]:
AR3.shape

(4, 2, 2)

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [55]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [60]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
np.random.rand(3, 2, 2)

array([[[0.71466338, 0.36393117],
        [0.63274972, 0.56452024]],

       [[0.50969958, 0.5800784 ],
        [0.02007438, 0.52244185]],

       [[0.60750626, 0.24050511],
        [0.7836613 , 0.73875828]]])

In [62]:
np.random.randint(1, 45, size=(5, 6))

array([[ 5, 39, 18, 12, 33, 39],
       [25,  3, 10, 33, 34, 21],
       [ 4, 19, 15, 17, 15, 38],
       [28,  2, 25, 18, 35, 20],
       [40, 23, 34, 42, 39,  2]])

In [63]:
np.random.seed(0)
np.random.choice(np.arange(1, 46), size = (5, 6), replace=False)

array([[31, 38, 28,  5, 11, 26],
       [29, 12, 39, 32, 30, 21],
       [42,  3, 44, 19, 16, 23],
       [17, 41,  9, 14,  6, 18],
       [33, 15, 36,  8, 35,  2]])

In [64]:
a1 = np.array([1, 3, 5, 7, 9])
a2 = np.array([2, 4, 6, 8, 10])

In [65]:
a1 + a2

array([ 3,  7, 11, 15, 19])

In [67]:
a2 - a1

array([1, 1, 1, 1, 1])

In [68]:
a1 * a2

array([ 2, 12, 30, 56, 90])

In [69]:
a2 / a1

array([2.        , 1.33333333, 1.2       , 1.14285714, 1.11111111])

In [70]:
a1 * 5

array([ 5, 15, 25, 35, 45])

In [71]:
a2 ** 2

array([  4,  16,  36,  64, 100])

In [73]:
a1.sum()

25

In [74]:
a2.mean()

6.0

In [75]:
a2.var()

8.0

In [76]:
a2.std()

2.8284271247461903

In [77]:
a2.min()

2

In [78]:
a2.max()

10

In [80]:
a1.cumsum()

array([ 1,  4,  9, 16, 25])

In [81]:
a1.cumprod()

array([  1,   3,  15, 105, 945])

In [86]:
A1 = np.array([1, 2, 3, 4]).reshape(2, 2)
A2 = np.array([1, 2, 3, 4]).reshape(2, 2)

In [87]:
A1.dot(A2)

array([[ 7, 10],
       [15, 22]])

In [88]:
np.dot(A2, A1)

array([[ 7, 10],
       [15, 22]])

In [89]:
A1 * A2

array([[ 1,  4],
       [ 9, 16]])

In [90]:
np.transpose(A1)

array([[1, 3],
       [2, 4]])

In [91]:
A2.transpose()

array([[1, 3],
       [2, 4]])

## Pandas

In [1]:
!ls -l

total 20
-rw-r--r-- 1 root root   723 Feb 22 08:31 PII.csv
-rw-r--r-- 1 root root 11370 Feb 22 08:31 PII.xlsx
drwxr-xr-x 1 root root  4096 Feb 16 16:35 sample_data


In [2]:
import pandas as pd

In [3]:
DF1 = pd.read_csv('PII.csv')

In [4]:
DF1

Name Gender  Age  Grade Picture BloodType  Height  Weight
0   송태섭     남자   21      3       무         B   179.1    63.9
1   최유정     여자   23      1       유         A   177.1    54.9
2   이한나     여자   20      1       무         A   167.9    50.2
3   김소혜     여자   23      3       무         O   176.1    53.5
4   서태웅     남자   24      4       무         B   176.1    79.8
5   정대만     남자   24      2       유         B   175.2    61.7
6   이정환     남자   22      4       무         B   169.1    69.8
7   채소연     여자   22      2       유        AB   169.9    52.7
8   강백호     남자   23      3       무         O   165.5    68.5
9   전소미     여자   22      2       유         O   161.9    52.3
10  변덕규     남자   21      1       무         A   163.2    55.5
11  정채연     여자   22      2       무         B   157.8    44.9
12  권준호     남자   24      4       유         O   166.9    61.7
13  채치수     남자   23      3       무        AB   181.8    85.9
14  윤대협     남자   22      2       유        AB   180.3    76.2
15  김세정     여자   21      1       무         O   155.5    44.9
16  신준섭     남자   23      1       무         A   168.9    62.7

In [5]:
DF2 = pd.read_excel('PII.xlsx')

In [6]:
DF2

Name Gender  Age  Grade Picture BloodType  Height  Weight
0   송태섭     남자   21      3       무         B   179.1    63.9
1   최유정     여자   23      1       유         A   177.1    54.9
2   이한나     여자   20      1       무         A   167.9    50.2
3   김소혜     여자   23      3       무         O   176.1    53.5
4   서태웅     남자   24      4       무         B   176.1    79.8
5   정대만     남자   24      2       유         B   175.2    61.7
6   이정환     남자   22      4       무         B   169.1    69.8
7   채소연     여자   22      2       유        AB   169.9    52.7
8   강백호     남자   23      3       무         O   165.5    68.5
9   전소미     여자   22      2       유         O   161.9    52.3
10  변덕규     남자   21      1       무         A   163.2    55.5
11  정채연     여자   22      2       무         B   157.8    44.9
12  권준호     남자   24      4       유         O   166.9    61.7
13  채치수     남자   23      3       무        AB   181.8    85.9
14  윤대협     남자   22      2       유        AB   180.3    76.2
15  김세정     여자   21      1       무         O   155.5    44.9
16  신준섭     남자   23      1       무         A   168.9    62.7

In [7]:
type(DF1)

pandas.core.frame.DataFrame

In [8]:
DF1.index

RangeIndex(start=0, stop=17, step=1)

In [9]:
DF1.columns

Index(['Name', 'Gender', 'Age', 'Grade', 'Picture', 'BloodType', 'Height',
       'Weight'],
      dtype='object')

In [10]:
DF1.values

array([['송태섭', '남자', 21, 3, '무', 'B', 179.1, 63.9],
       ['최유정', '여자', 23, 1, '유', 'A', 177.1, 54.9],
       ['이한나', '여자', 20, 1, '무', 'A', 167.9, 50.2],
       ['김소혜', '여자', 23, 3, '무', 'O', 176.1, 53.5],
       ['서태웅', '남자', 24, 4, '무', 'B', 176.1, 79.8],
       ['정대만', '남자', 24, 2, '유', 'B', 175.2, 61.7],
       ['이정환', '남자', 22, 4, '무', 'B', 169.1, 69.8],
       ['채소연', '여자', 22, 2, '유', 'AB', 169.9, 52.7],
       ['강백호', '남자', 23, 3, '무', 'O', 165.5, 68.5],
       ['전소미', '여자', 22, 2, '유', 'O', 161.9, 52.3],
       ['변덕규', '남자', 21, 1, '무', 'A', 163.2, 55.5],
       ['정채연', '여자', 22, 2, '무', 'B', 157.8, 44.9],
       ['권준호', '남자', 24, 4, '유', 'O', 166.9, 61.7],
       ['채치수', '남자', 23, 3, '무', 'AB', 181.8, 85.9],
       ['윤대협', '남자', 22, 2, '유', 'AB', 180.3, 76.2],
       ['김세정', '여자', 21, 1, '무', 'O', 155.5, 44.9],
       ['신준섭', '남자', 23, 1, '무', 'A', 168.9, 62.7]], dtype=object)

In [11]:
DF1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Name       17 non-null     object 
 1   Gender     17 non-null     object 
 2   Age        17 non-null     int64  
 3   Grade      17 non-null     int64  
 4   Picture    17 non-null     object 
 5   BloodType  17 non-null     object 
 6   Height     17 non-null     float64
 7   Weight     17 non-null     float64
dtypes: float64(2), int64(2), object(4)
memory usage: 1.2+ KB


In [12]:
DF1.head()

Name Gender  Age  Grade Picture BloodType  Height  Weight
0  송태섭     남자   21      3       무         B   179.1    63.9
1  최유정     여자   23      1       유         A   177.1    54.9
2  이한나     여자   20      1       무         A   167.9    50.2
3  김소혜     여자   23      3       무         O   176.1    53.5
4  서태웅     남자   24      4       무         B   176.1    79.8

In [13]:
DF1[0:5]

Name Gender  Age  Grade Picture BloodType  Height  Weight
0  송태섭     남자   21      3       무         B   179.1    63.9
1  최유정     여자   23      1       유         A   177.1    54.9
2  이한나     여자   20      1       무         A   167.9    50.2
3  김소혜     여자   23      3       무         O   176.1    53.5
4  서태웅     남자   24      4       무         B   176.1    79.8

In [14]:
DF1.tail(3)

Name Gender  Age  Grade Picture BloodType  Height  Weight
14  윤대협     남자   22      2       유        AB   180.3    76.2
15  김세정     여자   21      1       무         O   155.5    44.9
16  신준섭     남자   23      1       무         A   168.9    62.7

In [15]:
DF1[-3:]

Name Gender  Age  Grade Picture BloodType  Height  Weight
14  윤대협     남자   22      2       유        AB   180.3    76.2
15  김세정     여자   21      1       무         O   155.5    44.9
16  신준섭     남자   23      1       무         A   168.9    62.7

In [17]:
DF1.describe()

Age      Grade      Height     Weight
count  17.000000  17.000000   17.000000  17.000000
mean   22.352941   2.294118  170.135294  61.123529
std     1.169464   1.104802    7.853896  11.867894
min    20.000000   1.000000  155.500000  44.900000
25%    22.000000   1.000000  165.500000  52.700000
50%    22.000000   2.000000  169.100000  61.700000
75%    23.000000   3.000000  176.100000  68.500000
max    24.000000   4.000000  181.800000  85.900000

In [18]:
DF1.mean()

Age        22.352941
Grade       2.294118
Height    170.135294
Weight     61.123529
dtype: float64

In [19]:
type(DF1['Height'])

pandas.core.series.Series

In [21]:
DF1[['Height', 'Age']]

Height  Age
0    179.1   21
1    177.1   23
2    167.9   20
3    176.1   23
4    176.1   24
5    175.2   24
6    169.1   22
7    169.9   22
8    165.5   23
9    161.9   22
10   163.2   21
11   157.8   22
12   166.9   24
13   181.8   23
14   180.3   22
15   155.5   21
16   168.9   23

In [22]:
DF1.Height

0     179.1
1     177.1
2     167.9
3     176.1
4     176.1
5     175.2
6     169.1
7     169.9
8     165.5
9     161.9
10    163.2
11    157.8
12    166.9
13    181.8
14    180.3
15    155.5
16    168.9
Name: Height, dtype: float64

In [23]:
DF1['Height'].sum()

2892.2999999999997

In [24]:
DF1['Height'].mean()

170.1352941176471

In [25]:
DF1['Height'].var()

61.683676470588225

In [26]:
DF1['Height'].std()

7.8538956238664275

In [27]:
DF1.Height.min()

155.5

In [28]:
DF1.Height.max()

181.8

In [29]:
DF1.groupby(['BloodType']).mean()

Age     Grade      Height  Weight
BloodType                                         
A          21.750000  1.000000  169.275000  55.825
AB         22.333333  2.333333  177.333333  71.600
B          22.600000  3.000000  171.460000  64.020
O          22.600000  2.600000  165.180000  56.180

In [30]:
DF1.groupby(['BloodType'])['Height'].mean()

BloodType
A     169.275000
AB    177.333333
B     171.460000
O     165.180000
Name: Height, dtype: float64

In [31]:
DF1.Height[16]

168.9

In [32]:
DF1.Height[0:5]

0    179.1
1    177.1
2    167.9
3    176.1
4    176.1
Name: Height, dtype: float64